### ISSUE TITLE
Implement for_each() method on streams 

### ISSUE THREAD

**Issue by roymanigley** [asuiu/streamerate#1]
it should have a method on which we can iterate over the stream in the `streamerate.streams._IStream` class.  

something like:
```python
def for_each(self, f: Callable[[_K], None]) -> None:
    for entry in self.toList():
        f(entry)
```

**Comment by asuiu** [comment]
Fixed in [this commit](https://github.com/asuiu/streamerate/commit/c978cebdef24cb4ea26bc1c3b51597742ed90c45)
