### ISSUE TITLE
Not compatible with Python 3.8

### ISSUE THREAD

**Issue by kiranzo** [asuiu/streamerate#11]
I am trying to use another library that depends on this one on Python 3.8, and it gives this error during import:
```
    def shuffle(self, seed: Optional[Union[int | float | str | bytes | bytearray]] = None) -> "slist[_K]":
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
From [the internet](https://github.com/fastapi/typer/issues/371#issuecomment-1073649190):

> | was added in python 3.10, so not available in python 3.8.

So you either want to remove 'python 3.8/3.9' label from your latest releases, or make it actually compatible with older versions.

**Comment by asuiu** [comment]
@kiranzo totally agree.

Fixed in this commit: https://github.com/asuiu/streamerate/commit/6aad71938385285be9a59de3782085a16b1712bf

Deployed new version on PyPi: https://pypi.org/project/streamerate/1.1.1/

Issue fixed.
